"""Build reports/scalability/README.md from the raw JSON results (numbers are never typed by hand).

  .venv\\Scripts\\python deploy/scale/report.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
R = ROOT / "reports" / "scalability"


def load(name):
    p = R / name
    return json.loads(p.read_text()) if p.exists() else None


def fmt(v, nd=1):
    if v is None:
        return "-"
    if isinstance(v, float):
        return f"{v:,.{nd}f}"
    return f"{v:,}" if isinstance(v, int) else str(v)


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(fmt(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def scorer_stats(r):
    ds = r.get("docker_stats") or {}
    sc = [v for k, v in ds.items() if "scorer" in k]
    if not sc:
        return None, None, None
    return (round(sum(v["cpu_pct_mean"] for v in sc) / len(sc), 1), round(max(v["mem_mb_max"] for v in sc), 1),
            round(sum(v["cpu_pct_mean"] for k, v in ds.items() if "loadgen" in k), 1))


def main():
    env = load("environment.json") or {}
    md = ["# UVERA scalability results", "",
          "Measured on one laptop, not a cluster. Every number below is generated by `deploy/scale/report.py` from the raw "
          "JSON files in this folder. How to reproduce: `deploy/scale/README.md`.", ""]
    if env:
        md += ["## Hardware and setup", "", table(["item", "value"], [[k, v] for k, v in env.items()]), ""]

    rows = load("loadtest_transfer.json") or []
    if rows:
        md += ["## 1. Transfer scoring: concurrency x replicas", "",
               "`POST /score/transfer` through nginx; each request reads the sender and receiver features from Redis (Lua), "
               "computes the 19 AI-1 features, runs LightGBM + isotonic + conformal + novelty + policy, explains with TreeSHAP "
               "when the risk is not low, and queues the decision for Postgres (batched COPY). Closed-loop clients, 30 s per "
               "point after a 5 s warm-up, client inside the Docker network. Each scorer replica is limited to 1 vCPU.", "",
               "![latency](latency_vs_concurrency.png)", "", "![throughput](throughput_scaling.png)", ""]
        body = []
        for r in sorted(rows, key=lambda r: (r["replicas"], r["concurrency"])):
            cpu, mem, lg = scorer_stats(r)
            L = r.get("latency_ms", {})
            body.append([r["replicas"], r["concurrency"], r["rps"], L.get("p50"), L.get("p95"), L.get("p99"), L.get("max"),
                         f"{100 * r.get('error_rate', 0):.2f}%", cpu, mem])
        md += [table(["replicas", "clients", "req/s", "p50 ms", "p95 ms", "p99 ms", "max ms", "errors", "CPU %/replica", "RSS MB/replica"], body), "",
               "CPU % and memory per scorer replica are `docker stats` samples taken during each run (mean CPU over the "
               "replicas; 100% = the 1 vCPU limit). All services and the load generator share this laptop, so these runs do not isolate a single bottleneck.", ""]
        sample = rows[-1].get("docker_stats") or {}
        other = [[k.replace("uvera-scale-", ""), v["cpu_pct_mean"], v["mem_mb_max"]] for k, v in sorted(sample.items()) if "scorer" not in k]
        if other:
            md += [f"Other containers during the last run ({rows[-1]['replicas']} replicas, {rows[-1]['concurrency']} clients):", "",
                   table(["container", "CPU % (mean)", "memory MB (max)"], other), ""]

    mono, host = load("monolith_baseline.json"), load("host_vs_monolith.json")
    if mono:
        md += ["## 2. Before vs after (same Windows-host client, same transfers)", "",
               "Before = the existing monolithic FastAPI app (`backend/`, world + all engines in one process, "
               "`POST /v1/pause-check`). Its endpoint does more per call (counterfactual grid of 24 predictions, note check, "
               "brief, always-on TreeSHAP), so this compares the deployable architectures, not identical work.", "",
               "![before after](before_after.png)", ""]
        body = []
        for name, src in [("monolith (before)", mono), ("scale stack, 4 replicas (after)", host or [])]:
            for r in src:
                L = r.get("latency_ms", {})
                body.append([name, r["concurrency"], r["rps"], L.get("p50"), L.get("p95"), L.get("p99"), L.get("max"), r["errors"]])
        md += [table(["system", "clients", "req/s", "p50 ms", "p95 ms", "p99 ms", "max ms", "errors"], body), ""]
        if env.get("monolith_memory"):
            md += [f"Monolith memory: {env['monolith_memory']}. Monolith cold start: {env.get('monolith_startup', '-')}.", ""]

    ex = load("loadtest_explain.json")
    if ex:
        md += ["## 3. Cost of explanations (TreeSHAP) per request", ""]
        body = [[r["explain_mode"], r["replicas"], r["concurrency"], r["rps"], r["latency_ms"]["p50"], r["latency_ms"]["p95"],
                 r["latency_ms"]["p99"]] for r in ex]
        md += [table(["explain", "replicas", "clients", "req/s", "p50 ms", "p95 ms", "p99 ms"], body), ""]

    dbm = load("loadtest_dbmode.json")
    if dbm:
        md += ["## 4. Postgres write path: synchronous INSERT vs batched COPY", ""]
        body = [[r["db_write"], r["replicas"], r["concurrency"], r["rps"], r["latency_ms"]["p50"], r["latency_ms"]["p95"],
                 r["latency_ms"]["p99"], r["errors"]] for r in dbm]
        md += [table(["decision write", "replicas", "clients", "req/s", "p50 ms", "p95 ms", "p99 ms", "errors"], body), ""]

    mixed = load("loadtest_mixed.json")
    if mixed:
        md += ["## 5. Mixed workload (transfers + text checks + alert/case writes)", "",
               "70% transfer scoring, 20% AI-2 SMS check, 5% alert create (Postgres transaction + audit), 3% case link "
               "(advisory lock, find-or-create case, link alert, audit), 2% case read.", ""]
        body = []
        for r in mixed:
            body.append([r["replicas"], r["concurrency"], "ALL", r["rps"], r["latency_ms"]["p50"], r["latency_ms"]["p95"],
                         r["latency_ms"]["p99"], r["errors"]])
            for k, v in sorted(r["per_endpoint"].items()):
                L = v.get("latency_ms", {})
                body.append(["", "", k, v["rps"], L.get("p50"), L.get("p95"), L.get("p99"), v["errors"]])
        md += [table(["replicas", "clients", "endpoint", "req/s", "p50 ms", "p95 ms", "p99 ms", "errors"], body), ""]

    st = load("stream_ingest.json")
    if st:
        md += ["## 6. Stream ingestion (producer -> Redis Stream -> feature-worker -> online store)", "",
               "Lag = time from the producer's XADD to the event being applied in the online feature store (feature "
               "freshness). Every p2p transfer also gets a point-in-time feature snapshot for the drift monitor.", "",
               "![stream](stream_ingest.png)", ""]
        body = [[r.get("label", ""), r["n_workers"], r["target_rate"], r["producer"]["rate_achieved"], r["worker_events_per_s"],
                 r["lag_ms_p50_max_over_workers"], r["lag_ms_p95_max_over_workers"], r["lag_ms_p99_max_over_workers"],
                 r["events_processed"]] for r in st]
        md += [table(["run", "workers", "target ev/s", "produced ev/s", "applied ev/s", "lag p50 ms", "lag p95 ms", "lag p99 ms", "events"], body), ""]
        body = []
        for name, f in [("full warm-up days 0-99, pure-Python Redis parser", "stream_warmup_replay_purepython_parser.json"),
                        ("full warm-up days 0-99, hiredis parser", "stream_warmup_replay.json"),
                        ("shadow replay days 100-119 (2,500 ev/s target, scoring on)", "shadow_worker_stats.json")]:
            w = load(f)
            if w:
                body.append([name, w["events"], w["events_per_s"], w["batch_ms"]["p50"], w["batch_ms"]["p95"], w.get("redis_used_memory_mb")])
        if body:
            md += ["Worker throughput on longer runs (1 worker, 1 vCPU; batch = 500 events):", "",
                   table(["run", "events", "events/s", "batch p50 ms", "batch p95 ms", "Redis memory MB"], body), "",
                   "The pure-Python figure is a sample of 186,653 events from the first warm-up (stats were reset mid-run).", ""]

    sh = load("shadow_replay.json")
    if sh:
        md += ["## 7. Shadow-mode replay of the full test window (days 100-119)", "", sh["pipeline"], ""]
        body = []
        for name, s in sh["slices"].items():
            body.append([name, s["transfers_scored"], s["scams_in_window"], s["paused_red"], s["scams_paused_red"], s["false_pauses_red"],
                         s["recall_red"], s["precision_red"], s["false_pauses_per_1000_transfers"], s["recall_any_warning"]])
        md += [table(["slice", "transfers scored", "scams", "paused (red)", "scams paused", "false pauses", "recall (red)",
                      "precision (red)", "false pauses / 1000", "recall (any warning)"], body), ""]
        L = sh["latency_ms"]
        md += [table(["latency", "p50 ms", "p95 ms", "p99 ms", "max ms"],
                     [["end-to-end: produced -> decision", *[L["end_to_end_produce_to_decision"][k] for k in ("p50", "p95", "p99", "max")]],
                      ["scorer internal", *[L["scorer_internal"][k] for k in ("p50", "p95", "p99", "max")]]]), "",
               f"Replay span {sh['replay_span_s']} s, {sh.get('decisions_per_s')} decisions/s sustained, "
               f"{sh['scorer_replicas_used']} scorer replicas, model {sh['model_version']}.", ""]
        if sh.get("note"):
            md += [sh["note"], ""]

    par = load("parity.json")
    if par:
        md += ["## 8. Training-serving parity (online streaming features vs batch `build_ai1_features`)", "", par["what"], "",
               f"Rows: batch {par['rows']['batch']:,}, online {par['rows']['online']:,}, joined {par['rows']['joined']:,}.", ""]
        body = [[f, v["exact_pct"], v["within_1pct"], v["within_5pct"], v["nan_mismatch"], v["max_abs_diff"]] for f, v in par["per_feature"].items()]
        md += [table(["feature", "exact %", "within 1 %", "within 5 %", "NaN mismatches", "max abs diff"], body), "",
               "Not exact: `recipient_in_today_before` (99.92%): the batch builder counts only non-mule transfers, using the "
               "simulator's hidden `mule_flow` truth flag, which no live system can see; online counts every transfer "
               "(670 mule-flow transfers in the whole log). `amount_to_balance` is exact because the online store "
               "receives the daily start-of-day ledger snapshot; rebuilt from events alone it matched 37.9% exactly "
               "(70.4% within 1%), since the synthetic ledger has outflows that never appear as events.", ""]
        mb, mo = par["model_on_batch_features"], par["model_on_online_features"]
        body = []
        for sl in ("window", "unseen_customers_test_split"):
            for name, m in (("batch features", mb[sl]), ("online features", mo[sl])):
                body.append([sl, name, m["n"], m["positives"], m["roc_auc"], m["pr_auc"], m["recall_at_red"], m["red_rate"]])
        md += [table(["slice", "features", "n", "scams", "ROC-AUC", "PR-AUC", "recall at red", "red rate"], body), "",
               f"Same risk level for {par['score_agreement']['same_risk_level_pct']}% of transfers "
               f"({par['score_agreement']['risk_level_changes']} changed); max |raw score diff| "
               f"{par['score_agreement']['max_abs_raw_score_diff']}.", ""]

    dd = load("drift_demo.json")
    if dd:
        md += ["## 9. Drift monitoring demo (PSI, warn 0.1 / alert 0.2)", "", dd["what"], "", "![drift](drift_psi.png)", ""]
        cal = {"dow", "hour", "is_night"}
        body = []
        for p in dd["phases"]:
            psi = {k: v for k, v in p["drift"]["psi"].items() if v is not None}
            nc = sorted(((k, v) for k, v in psi.items() if k not in cal), key=lambda kv: -kv[1])
            body.append([p["name"], p["drift"]["status"], p["drift"]["max_psi"], nc[0][1] if nc else None,
                         ", ".join(f"{k} {v}" for k, v in nc[:3]), psi.get("dow"), p["drift"]["window_n"]])
        md += [table(["phase", "status", "max PSI", "max PSI excl. calendar", "top drifted (non-calendar)", "dow PSI", "window n"], body), "",
               "Reference = days 70-99 (the 30 days before go-live). The third phase has only 6 days of traffic in a "
               "window that slid past the 7-day boundary, so `dow` also reads high there: a window artifact, not a "
               "behaviour change; the receiver features are the real signal. With the train-split reference and a "
               "20,000-transfer window (about 5 days), even normal traffic alerted (`drift_shadow_window_train_reference.json`: "
               "dow 3.67, first_time_pair 0.34, sender_tenure_days 0.24), which is why the deployed reference is the last "
               "pre-deployment window and the window covers a full week.", ""]

    (R / "README.md").write_text("\n".join(md), encoding="utf-8")
    print("wrote", R / "README.md")


if __name__ == "__main__":
    main()
