-- UVERA transactional store (replaces the prototype SQLite file for decisions, alerts, cases and audit).
-- Synthetic data only.

CREATE TABLE IF NOT EXISTS transactions (
    event_id     BIGINT PRIMARY KEY,
    sim_t        BIGINT NOT NULL,
    sender       TEXT NOT NULL,
    receiver     TEXT NOT NULL,
    amount       NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    channel      TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS transactions_sender_idx ON transactions (sender, sim_t DESC);
CREATE INDEX IF NOT EXISTS transactions_receiver_idx ON transactions (receiver, sim_t DESC);

-- Every Pause Check decision (append-only). UUID keys are generated by the scorer replicas: no shared sequence.
CREATE TABLE IF NOT EXISTS decisions (
    id            UUID PRIMARY KEY,
    event_id      BIGINT,
    source        TEXT NOT NULL DEFAULT 'api',          -- api | shadow | loadtest
    sender        TEXT NOT NULL,
    receiver      TEXT NOT NULL,
    amount        NUMERIC(14, 2) NOT NULL,
    channel       TEXT,
    sim_t         BIGINT,
    p_calibrated  REAL NOT NULL,
    raw_score     REAL NOT NULL,
    risk_level    TEXT NOT NULL CHECK (risk_level IN ('low', 'medium', 'high')),
    state         TEXT NOT NULL,
    unsure        BOOLEAN NOT NULL,
    ood           BOOLEAN NOT NULL,
    model_version TEXT NOT NULL,
    latency_ms    REAL,
    reasons       JSONB,
    replica       TEXT,
    produced_at   TIMESTAMPTZ,                          -- when the event entered the stream (shadow mode)
    decided_at    TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS decisions_sender_idx ON decisions (sender, decided_at DESC);
CREATE INDEX IF NOT EXISTS decisions_receiver_idx ON decisions (receiver, decided_at DESC);
CREATE INDEX IF NOT EXISTS decisions_event_idx ON decisions (event_id);
CREATE INDEX IF NOT EXISTS decisions_time_brin ON decisions USING BRIN (decided_at);
CREATE INDEX IF NOT EXISTS decisions_flagged_idx ON decisions (decided_at DESC) WHERE risk_level <> 'low' OR unsure;

CREATE TABLE IF NOT EXISTS cases (
    id          BIGSERIAL PRIMARY KEY,
    status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'closed')),
    title       TEXT,
    priority    SMALLINT NOT NULL DEFAULT 3,
    n_alerts    INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cases_open_idx ON cases (updated_at DESC) WHERE status <> 'closed';

CREATE TABLE IF NOT EXISTS case_wallets (
    case_id  BIGINT NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    wallet   TEXT NOT NULL,
    role     TEXT NOT NULL DEFAULT 'receiver',
    PRIMARY KEY (case_id, wallet)
);
CREATE INDEX IF NOT EXISTS case_wallets_wallet_idx ON case_wallets (wallet);

CREATE TABLE IF NOT EXISTS alerts (
    id           BIGSERIAL PRIMARY KEY,
    decision_id  UUID,
    event_id     BIGINT,
    wallet       TEXT NOT NULL,
    kind         TEXT NOT NULL,
    level        TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'closed')),
    case_id      BIGINT REFERENCES cases (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS alerts_open_idx ON alerts (created_at DESC) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS alerts_wallet_idx ON alerts (wallet, created_at DESC);
CREATE INDEX IF NOT EXISTS alerts_case_idx ON alerts (case_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGSERIAL PRIMARY KEY,
    actor       TEXT NOT NULL,
    action      TEXT NOT NULL,
    entity      TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    detail      JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_entity_idx ON audit_log (entity, entity_id, created_at DESC);

-- Confirmed outcomes (fraud reports / chargebacks). Joined with decisions for shadow evaluation and as the
-- label source for retraining. In the replay it is loaded from the synthetic ground truth.
CREATE TABLE IF NOT EXISTS fraud_labels (
    event_id     BIGINT PRIMARY KEY,
    label_scam   SMALLINT NOT NULL,
    scam_family  TEXT,
    mule_flow    SMALLINT NOT NULL DEFAULT 0,
    unseen_customer BOOLEAN,
    labelled_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS model_deployments (
    replica      TEXT NOT NULL,
    model        TEXT NOT NULL,
    version      TEXT NOT NULL,
    sha256       TEXT NOT NULL,
    verified     BOOLEAN NOT NULL,
    started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (replica, model, started_at)
);
